//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Franthesk.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAIXA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAIXA()
        {
            this.MOVIMENTO = new HashSet<MOVIMENTO>();
        }
    
        public int CD_ID { get; set; }
        public string DT_Data { get; set; }
        public Nullable<double> VL_ValorDinheiroAdmin { get; set; }
        public Nullable<double> VL_ValorCartaoAdmin { get; set; }
        public Nullable<double> VL_ValorDinheiroFunc { get; set; }
        public Nullable<double> VL_ValorCartaoFunc { get; set; }
        public string NM_Status { get; set; }
        public Nullable<double> VL_ValorInicial { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVIMENTO> MOVIMENTO { get; set; }
    }
}
