//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Franthesk.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMISSAO
    {
        public int CD_ID { get; set; }
        public string DT_Data { get; set; }
        public Nullable<double> VL_Total { get; set; }
        public Nullable<double> VL_Comissao { get; set; }
    }
}
