//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Franthesk.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class frantheskEntities : DbContext
    {
        public frantheskEntities()
            : base("name=frantheskEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAIXA> CAIXA { get; set; }
        public virtual DbSet<COMISSAO> COMISSAO { get; set; }
        public virtual DbSet<MERCADORIA> MERCADORIA { get; set; }
        public virtual DbSet<MERCADORIA_VENDA> MERCADORIA_VENDA { get; set; }
        public virtual DbSet<MOVIMENTO> MOVIMENTO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<VENDA> VENDA { get; set; }
        public virtual DbSet<CATEGORIAS> CATEGORIAS { get; set; }
    }
}
