//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Franthesk.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MERCADORIA_VENDA
    {
        public int CD_ID { get; set; }
        public Nullable<int> CD_Mercadoria { get; set; }
        public Nullable<int> CD_Venda { get; set; }
        public Nullable<int> QT_Quantidade { get; set; }
    
        public virtual MERCADORIA MERCADORIA { get; set; }
        public virtual VENDA VENDA { get; set; }
    }
}
