//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Franthesk.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMENTO
    {
        public int CD_ID { get; set; }
        public string DT_Hora { get; set; }
        public Nullable<double> VL_Valor { get; set; }
        public string TX_Descricao { get; set; }
        public Nullable<int> CD_Caixa { get; set; }
    
        public virtual CAIXA CAIXA { get; set; }
    }
}
