//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Franthesk.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int CD_ID { get; set; }
        public string NM_Nome { get; set; }
        public string TG_Login { get; set; }
        public string NR_Senha { get; set; }
        public Nullable<int> CD_Admin { get; set; }
        public string NR_Tel { get; set; }
        public string TX_ENDE { get; set; }
    }
}
